{% set name = "kglobalaccel" %}
{% set version = "5.74.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/kglobalaccel-{{ version }}.tar.xz
  sha256: 492d0f4198dc7bbfcfaf518804d9a99d22ac49a27ffb3816d147d36be159318f

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('kglobalaccel', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - extra-cmake-modules >={{ version }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - xorg-libxext
    - xorg-libx11
    - libxcb
    - xcb-util-keysyms
    - qt
    - kcrash >={{ version }}
    - kconfig >={{ version }}
    - kcoreaddons >={{ version }}
    - kdbusaddons >={{ version }}
    - kwindowsystem >={{ version }}
  run:
    - libxcb

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5GlobalAccel.so

about:
  home: https://api.kde.org/frameworks/kglobalaccel/html/index.html
  license: LGPL-2.0-only AND LGPL-2.0-or-later AND LGPL-2.1-only AND LGPL-3.0-only AND LicenseRef-KDE-Accepted-LGPL
  license_file:
    - LICENSES/LGPL-2.0-only.txt
    - LICENSES/LGPL-2.0-or-later.txt
    - LICENSES/LGPL-2.1-only.txt
    - LICENSES/LGPL-3.0-only.txt
    - LICENSES/LicenseRef-KDE-Accepted-LGPL.txt
  summary: Global desktop keyboard shortcuts
  description: |
    KGlobalAccel allows you to have global accelerators that are independent
    of the focused window. Unlike regular shortcuts, the application's window
    does not need focus for them to be activated.
  dev_url: https://cgit.kde.org/kglobalaccel.git/tree

extra:
  recipe-maintainers:
    - scopatz
